In [76]:
import numpy as np
from scipy.spatial import distance
import pandas as pd

In [41]:
np.set_printoptions(precision=100, threshold=np.Inf)

In [50]:
X = np.array([0.7, 1.9, 4, 3.2, 5.1, 2.7, 4.8])
Y = np.array([21, 40, 29, 31, 18, 31, 26])

np.dot(X, Y) 

606.1999999999999

In [23]:
X = np.array([4, 7, 2, 1, 6, 1, 3, 3, 2, 8])
Y = np.array([2, 3, 8, 8, 8, 8, 7, 1, 0, 5])
distance.euclidean(X, Y)

13.820274961085254

In [24]:
X = np.array([4, 7, 2, 1, 6, 1, 3, 3, 2, 8])
Y = np.array([2, 3, 8, 8, 8, 8, 7, 1, 0, 5])
np.sum(np.abs(X - Y))

39

In [26]:
X = np.array([0, 1, 4, 6])
Y = np.array([[3, 0, 0], [1, 0, 4], [5, 6, 4], [3, 3, 6]])
X @ Y

array([39, 42, 56])

In [30]:
X = np.array([[3, -1, 0], [2, 1, -1], [1, 5, 4]])

np.linalg.det(X.T)

36.0

In [44]:
print(np.linalg.inv(np.array([[0, -1], [1, 0]])))

[[ 0.  1.]
 [-1. -0.]]


In [46]:
X = np.array([[1, 2, 6, 3], [1, 1, 4, 3], [-3, 4, -3, -3]])
Y = np.array([[1, 5], [1, 3], [6, 0], [-2, 4]])

(X @ Y).sum()

70

In [72]:
def snake(m, n) :
    
    X = np.zeros(shape=(m, n))
    X = np.column_stack((X, np.arange(1, m+1)))
    X[np.arange(0, m, 2), :-1] = X[:, -1] 
    return X

snake(3, 3)

array([[1., 2., 3., 4., 1.],
       [0., 0., 0., 0., 2.],
       [1., 2., 3., 4., 3.],
       [0., 0., 0., 0., 4.]])

In [75]:
def snake(m, n) :

    X = []

    for i in range(m) :
        if i % 2 == 0 :
            X.append([x + (i * n) for x in range(1, n+1)])
        else :
            X.append([x + (i * n) for x in range(1, n+1)][::-1])

    return X

snake(3, 4)

[[1, 2, 3, 4], [8, 7, 6, 5], [9, 10, 11, 12]]

In [ ]:
def calculate(products, cook) :
    
    N, M, K = list(cook @ products)

    print("Молоко, литры:", N)
    print("Яйца, штуки:", M)
    print("Мука, кг:", K)

In [79]:
data = pd.read_csv('penguins.csv')
data.dropna(inplace=True)
data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
4       3450.0  FEMALE  
5       3650.0    MALE

In [98]:
n = 0
k = 5

data.iloc[0, [2, 3]]

for _, row in data.iloc[np.argsort(data.iloc[:, [2, 3]].apply(lambda x : distance.euclidean(x, data.iloc[n, [2, 3]]), axis=1))[1:k+1], [2, 3]].iterrows() :
    print(row.tolist())

[39.0, 18.7]
[39.2, 18.6]
[38.9, 18.8]
[38.7, 19.0]
[39.6, 18.8]
