In [1]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [ ]:
data = np.array([(2,2),(2,1),(5,9),(-3,-10),(0,-5),(3,3)])

X = data[:, 0]
Y = data[:, 1]

(array([ 2,  2,  5, -3,  0,  3]), array([  2,   1,   9, -10,  -5,   3]))

In [9]:
mean_squared_error(Y, 3 * X - 5) * 6

19.0

In [11]:
X = np.c_[np.ones((5, 1)), np.array([[2, 0, 2, 2], [5, 3, 3, 5], [0, 3, 1, 2], [2, 8, 7, 6], [7, 1, 3, 2]])]
Y = np.array([1, 2, 3, 5, 8])
ws = np.array([-1,1,1,-1,1])

In [13]:
mean_squared_error(Y, X @ ws) * 5

62.0

In [19]:
X = np.c_[np.ones((5, 1)), np.array([[1, 9, 6, 3], [3, 1, 9, 6], [6, 3, 1, 9], [9, 6, 3, 1], [1, 0, 1, 0]])]
Y = np.array([2, 1, 3, -1, 1])

In [20]:
np.round(np.linalg.inv(X.T @ X) @ X.T @ Y, 2)

array([ 1.53, -0.32,  0.1 , -0.21,  0.37])

In [21]:
np.round(np.linalg.inv(X.T @ X + 1 * np.identity(5)) @ X.T @ Y, 2)

array([ 0.66, -0.25,  0.13, -0.14,  0.39])

In [29]:
x = np.array([3, 2, 2, 1])

def onehot_encoding(x) :

    res = []
    hashq = {}

    for i, el in enumerate(sorted(set(x.tolist()))) :
        if el not in hashq :
            hashq[el] = i

    for el in x.tolist() :
        res.append(np.concatenate([np.zeros(hashq[el], dtype=int), np.array([1], dtype=int), np.zeros(len(set(x)) - 1 - hashq[el], dtype=int)]))
    
    return np.asarray(res)

onehot_encoding(x)

array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]])

In [ ]:
x = np.array([[1]])

def minmax_scale(x) :
    if x.shape[0] == 1 :
        return np.zeros((1, x.shape[1]))
    return (x - x.min(axis=0)) / (x.max(axis=0) - x.min(axis=0))

minmax_scale(x)

array([[1.]])